name: CI
on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Git actions checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Process jest results with default
        if: always()
        uses: im-open/process-jest-test-results@v2.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: 'result.json'

